# List of options
set -g mouse on
set -g history-limit 10000
set -g @scroll-speed-num-lines-per-scroll 5
set -g status-position top

# Use vi keys in copy mode
set-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

#set kitty as default terminal and add compatibility options
set -g default-terminal "screen-256color"
set -gq allow-passthrough on
